### ISSUE TITLE
We need to do something with interstitial pages that google is going to add to goo.gl  links.

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/terroroftinytown-client-grab#12]
We have to add support for them.
https://en.wikipedia.org/wiki/Google_URL_Shortener#:~:text=Google%20will%20add%20an%20interstitial%20page%20to%20warn%20users%20about%20this%20starting%20August%2023%2C%202024.%5B10%5D

**Comment by chfoo** [comment]
The tracker was updated to include `?si=1` in the url template.
